let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
strip.setPixelColor(0, neopixel.colors(NeoPixelColors.White))
strip.setPixelColor(3, neopixel.colors(NeoPixelColors.White))
strip.show()
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 40)
music.playMelody("C D E F G A B C5 ", 120)
maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, 40)
strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Black))
strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Black))
strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Red))
strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Red))
strip.show()
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Whole))
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 40)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 40)
strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Black))
strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Orange))
strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Orange))
strip.show()
music.playMelody("C C D D E F G A ", 120)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 40)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 40)
strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Black))
strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Black))
strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Orange))
strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Orange))
strip.show()
music.playMelody("C5 C5 C5 B A B C5 B ", 120)
maqueen.motorStop(maqueen.Motors.All)
strip.showColor(neopixel.colors(NeoPixelColors.Black))
